import { AgentType } from '@prisma/client'
import type { AgentContext, HolyAgent } from '@/server/agents/core/agent'

class DefaultAgent implements HolyAgent {
  constructor(public readonly type: AgentType) {}

  async run(context: AgentContext) {
    void context
    return {
      title: `${this.type} proposal`,
      summary: `Automated proposal generated by ${this.type}.`,
      riskLevel: 'LOW' as const,
      actions: [{ type: 'RUN_QA' as const, summary: 'Run QA checks for recent changes.' }],
    }
  }
}

const registry = new Map<AgentType, HolyAgent>()

export function registerAgent(agentType: AgentType, agent: HolyAgent) {
  registry.set(agentType, agent)
}

export function getAgent(agentType: AgentType): HolyAgent {
  const existing = registry.get(agentType)
  if (existing) return existing
  const fallback = new DefaultAgent(agentType)
  registry.set(agentType, fallback)
  return fallback
}
